# Generated by Django 4.2.1 on 2023-05-11 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Performing Date')),
                ('song', models.CharField(choices=[('S', 'Stairway to Heaven'), ('H', 'Hotel California'), ('K', 'Kashmir')], default='S', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head_app.guitar')),
            ],
        ),
    ]
